In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
plt.rcParams['figure.facecolor'] = 'w'
# from scipy import stats
# from scipy.special import beta as beta_function

In [23]:
# transition matrix
T = np.array([[0.2, 0.3, 0.5], 
              [0.6, 0.0, 0.0],
              [0.2, 0.7, 0.5]])

# initial probability distribution: pure state 2
x0 = np.array([[0], 
               [1],
               [0]])

In [24]:
np.dot(T,x0)

array([[0.3],
       [0. ],
       [0.7]])

In [25]:
np.dot(T, np.dot(T,x0) )

array([[0.41],
       [0.18],
       [0.41]])

In [28]:
n_steps = 10
xn = x0
for _ in range(n_steps):
    print(xn.T)
    xn = np.round(np.dot(T, xn), 2)

[[0 1 0]]
[[0.3 0.  0.7]]
[[0.41 0.18 0.41]]
[[0.34 0.25 0.41]]
[[0.35 0.2  0.45]]
[[0.36 0.21 0.43]]
[[0.35 0.22 0.43]]
[[0.35 0.21 0.44]]
[[0.35 0.21 0.44]]
[[0.35 0.21 0.44]]


In [33]:
np.linalg.eig(T)

(array([ 1.  +0.j       , -0.15+0.3122499j, -0.15-0.3122499j]),
 array([[-0.58746336+0.j        , -0.16984156+0.35355339j,
         -0.16984156-0.35355339j],
        [-0.35247801+0.j        ,  0.67936622+0.j        ,
          0.67936622-0.j        ],
        [-0.72845456+0.j        , -0.50952467-0.35355339j,
         -0.50952467+0.35355339j]]))

In [34]:
from scipy.linalg import eig as eigenvetors

In [50]:
eigenvalues, eigenvectors = eigenvetors(T)
eigenvalues

array([ 1.  +0.j       , -0.15+0.3122499j, -0.15-0.3122499j])

In [52]:
np.round(eigenvectors, 3)

array([[-0.587+0.j   , -0.17 +0.354j, -0.17 -0.354j],
       [-0.352+0.j   ,  0.679+0.j   ,  0.679-0.j   ],
       [-0.728+0.j   , -0.51 -0.354j, -0.51 +0.354j]])

In [55]:
eigenvector1 = -eigenvectors[:,0].real
# eigenvector1 /= -np.sqrt(np.dot(eigenvector1, eigenvector1.T))
eigenvector1

array([0.58746336, 0.35247801, 0.72845456])

In [56]:
np.dot(eigenvector1, eigenvector1.T)

1.0

In [ ]:
0.58746336, 0.35247801, 0.72845456